### ISSUE TITLE
Cannot use custom scheduling function

### ISSUE THREAD

**Issue by chpill** [clj-commons/citrus#25]
Hello!

I see that the reconciler accepts a batched-update function, which default to `js/requestAnimationFrame` (https://github.com/roman01la/citrus/blob/056eb0ad0c5787fa26d208cf874e0eca95ce68d7/src/citrus/core.cljs#L33).

But in the scheduling code, the `js/cancelAnimationFrame` function is hardcoded (https://github.com/roman01la/citrus/blob/056eb0ad0c5787fa26d208cf874e0eca95ce68d7/src/citrus/reconciler.cljs#L13), which effectively prevents someone from providing another scheduling function.

Maybe we could provide the `:batched-update` as a map `{:schedule-fn ... :release-fn ...}` which would default to `{:schedule-fn js/requestAnimationFrame :release-fn js/cancelAnimationFrame}` ?

For example, in my current project I'd really like to be able to use `{:schedule-fn js/setTimeout :release-fn js/clearTimeout}` (which is more or less what reframe does).

Happy to provide a PR if you like the idea!

**Comment by roman01la** [comment]
Looks good to me. I will merge a PR to fix this.
On the side note, is there any reason you prefer settineout rather than rAF?

**Comment by chpill** [comment]
Good! I will provide a PR soon.

Regarding requestAnimationFrame, assuming that your js code is running inside of a web page, what happens when the tab goes in the background? Wouldn't that completely halt the processing of events?

Admittedly, setTimeout also has issues in background tabs (https://content.pivotal.io/blog/chrome-and-firefox-throttle-settimeout-setinterval-in-inactive-tabs) but for most cases the 1s minimum delay is probably okay.

**Comment by roman01la** [comment]
OH, you are right. Maybe this setTimeout should be a standard scheduling fn then?

**Comment by chpill** [comment]
I guess it would be a safer default... but I guess it also means less batching?

As batching goes, an even better strategy would probably be something along the line of `{:schedule-fn js/requestIdleCallback :release-fn js/cancelIdleCallback}`. It seems even possible to provide a timeout to `requestIdleCallback`. But it is sadly not very widespread as of today https://developer.mozilla.org/en-US/docs/Web/API/Window/requestIdleCallback

I can make a PR setting `js/setTimeout` as a default if you think it is not likely break current users of the library.

**Comment by roman01la** [comment]
> but I guess it also means less batching?

The timeout could be set to 16ms by default, so it should have more or less the same effect

**Comment by roman01la** [comment]
As for using `rIC` for batching state updates, I don't think it's a good fit. Instead it would be good for executing those updates. For this there's `:chunked-updates` option, but it's not used anywhere yet.

**Comment by chpill** [comment]
I opened a pull request, but not for the change in the default behaviour of the batching.

I have thought about it during the week-end, just using `js/setTimeout` would not work: Imagine you use `{:schedule-fn #(js/setTimeout % 16) :release-fn js/clearTimeout}`, and you do a `(js/setInterval #(citrus/dispatch! reconciler ...) 10)` to dispatch every 10ms. Doing this would prevent all dispatch (except `dispatch-sync!`) on the reconciler! Because every call to `dispatch!` will cancel the next batch-update (that should have happened, in theory, 6ms later), and schedule another one 16ms later... Then again 10ms later the batched-update is canceled etc.

With `js/requestAnimationFrame`, the batched-update is guaranteed to happen during the next frame, so most of the time, in the next 16ms.


I guess what we need to do is provide a default batched-update that uses something like `goog.functions.throttle` to make sure we don't delay an update more than a predetermined duration?

**Comment by roman01la** [comment]
Are you sure that rAF doesn't behave the same in when canceling the timeout? A quick test shows that it does
```js
const id = requestAnimationFrame(() => console.log("RAF"))
cancelAnimationFrame(id)
```

**Comment by roman01la** [comment]
Ah, ok I get it now, so rAF works because its call time is bound to browser's _frame_.

So what about throttling? Is it a possible solution for `setTimeout`-based scheduling?

**Comment by chpill** [comment]
Yes, I think we need to change the way the `schedule-update!` works (to avoid canceling the update already scheduled). I'll try to have a go at it by the end of the week.

**Comment by roman01la** [comment]
@chpill  So what do we have here? :)

**Comment by chpill** [comment]
https://github.com/roman01la/citrus/pull/27

Sorry for the delay :)

**Comment by martinklepsch** [comment]
Closing this as per https://github.com/clj-commons/citrus/pull/27#issuecomment-644710265
