### ISSUE TITLE
Difference in subscriptions with reducers between CLJ and CLJS

### ISSUE THREAD

**Issue by DjebbZ** [clj-commons/citrus#39]
Hi,

I think I spotted a bug: 
- in `citrus/cursor.cljs`, the `IDeref` implementation is always calling `get-in` first, then the `reducer` (with a fallback to `identity` if not provided).
- in `citrus/resolver.clj`, the `clojure.lang.IDeref` does things differently depending on whether a reducer is present or not. If not present, it just calls `get-in`. But if there's a reducer, it calls `reducer` first, then `get-in`, when I think it should be the other way around.

So for a subscription like this:

``` clojure
(defn products-count [reconciler]
  (citrus/subscription reconciler [:products :list] count))
```

In CLJ it will call `(-> data count (get-in [:products :list]))`, whereas in CLJS it will do `(-> data (get-in [:products :list]) count)`.

Am I right ?

**Comment by roman01la** [comment]
fixed in #40
